### ISSUE TITLE
Desktop app won't sync

### ISSUE THREAD

**Issue by avramovic** [a85/POSTMan-Chrome-Extension#4249]
## App Details:

```
Postman for Mac
Version 6.0.7
OS X 17.4.0 / x64
```

## Issue Report:
 1. Did you encounter this recently, or has this bug always been there: since moving from chrome to desktop app
 2. Expected behaviour: it should sync
 3. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):

```
    error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (requester.js:75263)
    at EventEmitter.108.EventEmitter.emit (common.js:17099)
    at _dispatch (common.js:24502)
    at EventEmitter.<anonymous> (common.js:24512)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
```

 4. Screenshots (if applicable)

<img src="https://i.imgur.com/9X0P7pu.png" />

(stuck at connecting for more than 40 minutes)

Everything was working fine when I was using chrome app. I just installed desktop app for mac, logged in successfully, but it won't sync my collections

**Comment by sivcan** [comment]
@avramovic - Can you try restarting the app ?
Is this issue still happening for you ?

**Comment by avramovic** [comment]
@sivcan I have restarted it several times so far. I have also restarted it just now, still stuck at connecting

**Comment by avramovic** [comment]
@sivcan It works! I don't know how/why but it popped up a window saying that my session has expired and made me login again and it synced immediately after the login!

**Comment by sivcan** [comment]
@avramovic - Cool, we'll check on our end if something weird was happening.
Glad that it's resolved for you.

**Comment by anreddy018** [comment]
Hi sivcan,  Could you please tell me what change you made make it work. Please explain configurations if possible. 
appreciated

Thanks

**Comment by FlanderJam** [comment]
@sivcan Is this an appropriate place to bring this up? I looked elsewhere and this ticket was the closest to the issue I'm encountering. Is there a way we can re-open this issue or clone it?

I am encountering this issue on Windows as well and have not been able to resolve. Occasionally sync will occur but has always returned to failing.

App Details
=======
```
Postman for Windows
Version 6.0.10
win32 10.0.16299 / x64
```
Issue Details
========
* I only began encountering this issue after upgrading from 5.5.2 to 6.0.10. Prior to this upgrade, syncing worked as expected across several Windows PCs all running Windows 10 Pro.
* Current behaviour: Launching the app will show "CONNECTING" for sync status indefinitely. My collections and requests are never synced. Furthermore, on one of my PCs, while using Postman, it continually prompts me to re-sync because the server and my local copy are 'Out-of-sync' even though no changes have occurred.
* Expected behaviour: Launching the app will show "CONNECTING" only until the app has successfully connected, at which point a sync will occur and the sync status will display "SYNCED". User will have all collections and requests that had been saved.
* Here are the console logs: 
```
 ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs.
================================================================
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:560264 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:560264
requester.js:368809 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback 
    at EventEmitter.108.EventEmitter.emit 
    at _dispatch 
    at EventEmitter.<anonymous> 
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
2requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:155489 Invalid lifecycle state switch for workspace undefined & state deleting
setLifecycle @ requester.js:155489
requester.js:141163 Successfully received bootstrap data Object
requester.js:238086 Publishing offline changes to sync client Array[0]
requester.js:41890 Could not perform update on UserListStore. id is missing in definition.
update @ requester.js:41890
requester.js:41889 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41889
requester.js:410163 You tried to return focus to null but it is not in the DOM anymore
exports.returnFocus @ requester.js:410163
```

**Comment by sivcan** [comment]
@kwilmot - We'll take a look into it and get back to you.
However, as a quick fix - can you try logging out and logging in back again ?

Also, disconnecting the Wifi on your machine and reconnecting it might be an even faster temporary fix till we're looking into this issue.

If you've already tried that then let me know if it doesn't help you for now.

**Comment by FlanderJam** [comment]
@sivcan Thanks for the quick response.

I tried logging out and logging back in. This did not resolve the issue.

However, disconnecting Wifi and then reconnecting seemed to have resolved the issue on both of my computers.

**Comment by abdurrahmanarikan** [comment]
I have still same issue the postman says many times: 

Trying to reconnect to sync... Any changes made while offline will sync once you are back online..

I have solid Internet connection and tried to use above solutions but did not work. Can you help ?

**Comment by Ustingit** [comment]
@abdurrahmanarikan  i have this issue a few times per week. Log out and log in again works fine always for desktop client. Synch is quite slow and u have to wait a few minutes after log-in till postman pulls all data.

**Comment by mydogger** [comment]
yeah, Log out and log in again works fine, but the data is gone.

**Comment by danmutblix** [comment]
1. Go to settings -> data -> export all your data to json
2. Uninstall Postman
3. Delete %APPDATA%\Postman
4. Install Postman 
5. Go to settings -> import your dump
