### ISSUE TITLE
Cannot find module 'circular-json'

### ISSUE THREAD

**Issue by echo66** [a85/POSTMan-Chrome-Extension#5093]
**Describe the bug**
I'm using Fedora 28. I'm unable to start Postman. When I try to run it in my terminal, this is the output:
```
./Postman 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'circular-json'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/echo66/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/echo66/Postman/app/resources/app/main.js:8:20)
    at Object.<anonymous> (/home/echo66/Postman/app/resources/app/main.js:621:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**To Reproduce**
1. Download the postman at https://app.getpostman.com/app/download/linux64
2. Unzip the downloaded file.
3. Open the terminal in postman root directory.
4. Run `./Postman`
5. See error

**Expected behavior**
I was expecting postman app to open without any issues.

**Screenshots**

**App information (please complete the following information):**
 - OS: Fedora 28

**Additional context**

**Comment by pcsontos** [comment]
Same problem on my side. :-(

**Comment by SamvelRaja** [comment]
@echo66  @pcsontos 
Request you guys to completely remove the postman and download freshly from https://www.getpostman.com/apps
The issue is, some of the old files are not replaced properly.

Closing this for now, feel free to re-open if you still face the issues.

**Comment by tbuehlmann** [comment]
I just followed the steps @echo66 took and got the same result. I'm on Ubuntu 18.04.

**Comment by MikhailKlemin** [comment]
Yeah, does not launches on Ubuntu 18.04 and I also had to install Canbera gtk `sudo apt-get install libcanberra-gtk-module` 

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'circular-json'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/home/mike/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mike/Postman/app/resources/app/main.js:7:20)
    at Object.<anonymous> (/home/mike/Postman/app/resources/app/main.js:552:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by Offlein** [comment]
Experiencing this in Ubuntu 18.04 and `libcanberra-gtk-module` does not fix it for me.

**Comment by jaypozo** [comment]
I'm having the same issue on Ubuntu 16.04. I've downloaded the latest files and still have the issue.

**Comment by tobikl1** [comment]
I am experiencing the same on Fedora 28 with 
- Postman 6.4.4
- Postman 6.5.2

followed the installation instructions on the homepage, yet got this exception. Since it appears to be a nodejs app, i tried to navigate to Postman/app/resources/app and called npm i, trying to resolve missing dependencies. For this i get the exception

``npm WARN deprecated circular-json@0.3.0: CircularJSON is in maintenance only, flatted is its successor.``
``npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.``
``npm ERR! code ENOLOCAL``
``npm ERR! Could not install from "../../../../../var/lib/buildkite-agent/builds/postman-ci-agent-linux-build/postman/app-package-and-deploy/src/logger" as it does not contain a package.json file.``
`` ``
``npm ERR! A complete log of this run can be found in:``
``npm ERR!     /home/<userhome>/.npm/_logs/2018-11-20T15_18_11_417Z-debug.log``

i also tried to install missing dependencies manually by calling from the same folder

``npm i circular-json``

which lead to following error when trying to start postman next:

``A JavaScript error occurred in the main process``
``Uncaught Exception:``
``Error: Cannot find module 'lodash'``
``    at Module._resolveFilename (module.js:485:15)``
``    at Function.Module._resolveFilename (/opt/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)``
``    at Function.Module._load (module.js:437:25)``
``    at Module.require (module.js:513:17)``
``    at require (internal/module.js:11:18)``
``    at Object.<anonymous> (/opt/Postman/app/resources/app/main.js:8:9)``
``    at Object.<anonymous> (/opt/Postman/app/resources/app/main.js:549:3)``
``    at Module._compile (module.js:569:30)``
``    at Object.Module._extensions..js (module.js:580:10)``
``    at Module.load (module.js:503:32)``

and finally tried to resolve it by calling 
``npm i lodash``

which ultimately caused following exception when starting postman:

``A JavaScript error occurred in the main process``
``Uncaught Exception:``
``Error: Cannot find module './services/electronProxy'``
``    at Module._resolveFilename (module.js:485:15)``
``    at Function.Module._resolveFilename (/opt/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)``
``    at Function.Module._load (module.js:437:25)``
``    at Module.require (module.js:513:17)``
``    at require (internal/module.js:11:18)``
``    at Object.<anonymous> (/opt/Postman/app/resources/app/main.js:11:21)``
``    at Object.<anonymous> (/opt/Postman/app/resources/app/main.js:549:3)``
``    at Module._compile (module.js:569:30)``
``    at Object.Module._extensions..js (module.js:580:10)``
``    at Module.load (module.js:503:32)``

not sure wether what i did had any chance of working in the first place.

would be nice to get some fix for this since i really like postman and would like to continue using it after switching from windows to linux.

Best regards,

Tobi

**Comment by qortex** [comment]
Similar kind of error for me, fresh Fedora 29 install, running fresh Postman downloaded from the website fails with:

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Cannot find module './services/electronProxy'
>     at Module._resolveFilename (module.js:485:15)
>     at Function.Module._resolveFilename (/home/mic/dev/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
>     at Function.Module._load (module.js:437:25)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/mic/dev/Postman/app/resources/app/main.js:11:21)
>     at Object.<anonymous> (/home/mic/dev/Postman/app/resources/app/main.js:549:3)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)

**Comment by realflash** [comment]
@SamvelRaja

This issue occurs on a machine which has never had Postman installed so it isn't to do with upgrading. 

I downloaded and installed version [6.5.3](https://dl.pstmn.io/download/version/6.5.3/linux64) which worked OK, and then re-installed 6.6.1 which then worked fine too (both extracted to the same place). So maybe putting down 6.5.3 creates some file which is missing in 6.6.1?

**Comment by ermlauri** [comment]
I had same issue on fresh Ubuntu 18.04. First time, when extracting tar.gz in GUI and the copying the folder I got an error that one .js file could not be found. After that got the same circular-json error.

Solution was to exctract using terminal:
`tar -xvzf ./Postman-linux-x64-6.6.1.tar.gz`

Third time, to verify the issue, I just extracted the file in GUI and tried to run it, but got the same error. Then copied the same "Postman" folder out from "Postman-linux-x64-6.6.1" and was able to start the application. So, basically got the opposite result than in the first attempt.

PS. I Also had to install `libcanberra-gtk-module`

**Comment by hakuno** [comment]
I followed that

>  tar -xvzf ./Postman-linux-x64-6.6.1.tar.gz

I didn't need to download this `libcanberra` on Fedora 30. Thanks!

**Comment by ericlima** [comment]
people,

I'm using Fedora 29 and the problem was occured until I used:

tar -xvzf ./Postman-linux-x64-7.2.2.tar.gz

now is working fine !

**Comment by yuanzhou** [comment]
Same here. Installed on Fedora30 by following the instructions at: https://learning.getpostman.com/docs/postman/launching_postman/installation_and_updates/

Had the same issue with not being able to start the postman. 

Did `tar -zxvf Postman-linux-x64-7.6.0.tar.gz` and now it's working.

**Comment by alik-takipi** [comment]
Downloaded latest `Postman-linux-x64-7.19.1.tar.gz` from https://www.postman.com/downloads/ and got the error:

```
alik@ooalik:~$ /home/alik/Apps/Postman/Postman
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'circular-json'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/alik/Apps/Postman/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/alik/Apps/Postman/app/resources/app/main.js:7:20)
    at Object.<anonymous> (/home/alik/Apps/Postman/app/resources/app/main.js:751:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

**Comment by fdoyen** [comment]
Damn, extracting in CLI and not with GUI solved the problem, like the others. Last time I do something with GUI. CLI ftw ! Thanks mate.

Worked on Lubuntu 18.04 LXDE

**Comment by doom-fr** [comment]
But how is it possible ?? It's a Linux bug ?
If yes, does someone reported this bug to Ubuntu, Fedora and maybe more ?

**Comment by rafalglowacz** [comment]
Just run into this issue in Ubuntu 20.04.1 LTS and simply extracting the archive did the job.

@ymeramees 

> First time, when extracting tar.gz in GUI and the copying the folder I got an error that one .js file could not be found. After that got the same circular-json error.

I had the same thing, but apparently it was caused by moving the folder before it was fully extracted. Some UI elements in Ubuntu are pretty bad, in this instance it was a tiny progress indicator that I didn't notice until I was looking for it on the second attempt.

**Comment by wawasm** [comment]
npm i flatted - it works for me
