### ISSUE TITLE
Postman 6 pinning CPU on Linux

### ISSUE THREAD

**Issue by lucasyvas** [a85/POSTMan-Chrome-Extension#4237]
## App Details:
```
Postman for Linux
Version 6.0.6
linux 4.13.0-36-generic / x64
```

## Issue Report:
 1. Postman eating CPU. Issue surfaced immediately after upgrading from Postman 5 to 6
 2. Expect it doesn't eat endless CPU
 3. Console logs:
```
 ================================================================
     o
   (/) P O S T M A N
   ^

   Go to View -> Show Postman Console to check your script logs.
================================================================
requester.js:41747 Could not find on CollectionStore. Missing or invalid parameter.
find @ requester.js:41747
requester.js:559008 Check that entitites shown here should only be personal entites
componentWillMount @ requester.js:559008
requester.js:367780 error fetching Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (requester.js:75263)
    at EventEmitter.108.EventEmitter.emit (common.js:17099)
    at _dispatch (common.js:24502)
    at EventEmitter.<anonymous> (common.js:24512)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
requester.js:75263 Uncaught (in promise) Error: Could not fetch from sync. Socket not connected.
    at SyncRemoteFetcherService._dispatchCallback (requester.js:75263)
    at EventEmitter.108.EventEmitter.emit (common.js:17099)
    at _dispatch (common.js:24502)
    at EventEmitter.<anonymous> (common.js:24512)
    at emitTwo (events.js:106)
    at EventEmitter.emit (events.js:191)
2requester.js:41747 Could not find on CollectionStore. Missing or invalid parameter.
```
 4. Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/3365616/36625638-3dcfa7b6-18d8-11e8-9682-95d244397d23.png)

To reproduce, simply open Postman. I'm using Ubuntu 17.10

**Comment by sivcan** [comment]
@lucasyvas - I tried to reproduce this issue by using Postman 6 on Ubuntu 17.10 for an hour and even leaving it idle for a long time but was not able to reproduce it.
![image](https://user-images.githubusercontent.com/12631777/36625958-b20c34e2-194f-11e8-8c97-50bed7a59789.png)

Is this happening every time for you ?
Even after a few minutes, the CPU consumption stays at the peak ?

**Comment by lucasyvas** [comment]
I left it running for several minutes and it never relented. I also tried quitting and opening several times with same result. I will try rebooting for good measure to see what's up and report back

**Comment by sivcan** [comment]
@lucasyvas - Okay sure. Let me know!

**Comment by lucasyvas** [comment]
It's the same result... about 4 listed processes. Top one is always over 100%, other 3 ranging from 20% through 60%

I'll be up working in the morning (PST) to check and see if there are any other troubleshooting recommendations. Fortunately I don't think I will require Postman on this box for a few days, but I'm ready to try whatever to help diagnose it, time permitting.

It seems silly to try re-installing it, but I could.

**Comment by sivcan** [comment]
@lucasyvas - Thanks, so will be needing logs from you.

Steps : 
1. Launch the Postman App.
2. In the Menu Bar click on View > Developer > **View Dev Tools (Shared)** 
**Note** : Need  you to launch the dev tools for the 'Shared' view 
3. View > Developer > **View Dev Tools (Current View)**

Share the console logs as log files for both the dev tool windows.
Thanks!

**Comment by lucasyvas** [comment]
OK, here's both:

[postman-current-view.log](https://github.com/postmanlabs/postman-app-support/files/1754600/postman-current-view.log)
[postman-shared.log](https://github.com/postmanlabs/postman-app-support/files/1754601/postman-shared.log)

**Comment by numaanashraf** [comment]
@lucasyvas Thanks for helping us triage this. We can confirm there is a performance issue in Postman 6.0.x version which affects users without an account or while the application is trying to connect to our sync service. We are working on rolling out a fix for this as soon as possible.

**Comment by lucasyvas** [comment]
Happy to be able to help identify it!

👍

**Comment by numaanashraf** [comment]
@lucasyvas We've rolled out the fix in the latest version on our Canary channel (v6.0.7-canary01) - https://www.getpostman.com/canary. Would it be possible to download the Canary app and let us know if the issue is resolved at your end?

**Comment by lucasyvas** [comment]
There's still the uncaught socket error, but CPU is A-OK now!

**Comment by numaanashraf** [comment]
Glad to know @lucasyvas, and thanks again. 😃 We'll roll out this fix to our stable channel soon.

**Comment by anreddy018** [comment]
getting  : Postman error :  Could not fetch from sync. Socket not connected. Any help much appreciated.

Thanks

**Comment by sivcan** [comment]
@anreddy018 - I think that error must be appearing for the moment the app boots up.
Are you experiencing any issue with the sync apart from this error in console ? 
Does the orange icon on the left top bar of the app say 'In Sync' ?

**Comment by anreddy018** [comment]
@sivcan , I Can see the InSync is connecting... and getting error : Could not fetch from sync. Socket not connected. Could you please advise if have any work around.

Thanks
