### ISSUE TITLE
Mac app 4.5.0 Collection runner folder, ui environment, folder re-arrange, sugar js

### ISSUE THREAD

**Issue by pgg** [a85/POSTMan-Chrome-Extension#2222]
1. Postman Version: 4.5.0
2. App (Chrome app or Mac app): Mac app
3. OS details: OS X 10.11.6
4. Is the Interceptor on and enabled in the app: No
5. Did you encounter this recently, or has this bug always been there: Since 4.5.0
6. Expected behaviour: More complex than just expected
7. Console logs (http://blog.getpostman.com/2014/01/27/enabling-chrome-developer-tools-inside-postman/ for the Chrome App, View->Toggle Dev Tools for the Mac app):
8. Screenshots (if applicable)

Many issues encountered in this version:
1. In the collection runner, selecting a single folder inside a collection and clicking run, executes none of the tests in the folder. Runner only works when executing the entire collection, and then there is no way of controlling the execution order because folders can't be re-arranged . . .
2. In individual tests: postman.clearEnvironmentVariables(); -> clears the environment dictionary as can be seen with console.log(environment), but the app version persists still (when clicking on the eye or manage environments). The local and global environments behaviour is erratic in the ui.
3. Need to be able to re-arrange the folders in collections.
4. SugarJS does not work in the test sandbox

**Comment by czardoz** [comment]
@pgg Can you elaborate on the SugarJS bit? What exactly is not working? Can you post a sample code snippet that does not work?

**Comment by pgg** [comment]
Maybe I am just using it wrong, not all that familiar with SugarJS. In the Pre-request Script:

`Object.every({a:'a',b:'b'}, /[a-z]/);` fails with:

There was an error in evaluating the Pre-request Script:  TypeError Object.every is not a function. And:

`Sugar.Object.every({a:'a',b:'b'}, /[a-z]/);` fails with:

There was an error in evaluating the Pre-request Script:  ReferenceError Sugar is not defined

**Comment by czardoz** [comment]
@pgg `Object.every` seems to be a new method added in Sugar v2.x.x. For backwards compatibility, Postman's sandbox contains Sugar v1.x.x. 

Did any of your existing scripts stop working after upgrading to 4.5.0?

**Comment by davereimer** [comment]
I am also seeing the same issue with the Sugar Date functions.

```
var d = new Date();
var weekday = d.format("{Weekday}");
```

> There was an error in evaluating the Pre-request Script:  TypeError d.format is not a function

This is a Sugar v1.x.x function and it was working before I upgraded to 4.5.0

**Comment by pgg** [comment]
Same for:

```
Object.each({ foo: 'bar' }, function(k, v) {
  console.log('key is ', k, ' and value is ', v);
});
```

Which is a v1.5.0 feature . . .

**Comment by shamasis** [comment]
1. Fixed in 4.5.1
2. There's setting to turn on or off the persistence of variables post a run.
3. Feature request we have in our mid term roadmap.
4. We're following this. This has been reported in other issues. Duplicate in this thread. 

Hope closing this issue is now okay. If point 1 still does not work in 4.5.1, feel free to reopen.
