### ISSUE TITLE
GRPC request's protobuf import path is not working in postman 10.23.1 version.

### ISSUE THREAD

**Issue by ChoSeoHwan** [a85/POSTMan-Chrome-Extension#12654]
### Is there an existing issue for this?

- [X] I have searched the tracker for existing similar issues and I know that duplicates will be closed

### Describe the Issue

Postman 10.23.1 below error occurred when i use protobuf import path.

```
We could not find some of the files imported by the .proto file. Specify import paths to those unresolved files using the options below.
Details: unresolved import: notification/notification/common/notification_code.proto
```

- import file : {source_root}/notification/endpoint/presentation/service.proto
- import paths : {source_root}/

However, it works normally in lower versions.

### Steps To Reproduce

1. Write file 

***notification/endpoint/presentation/service.proto***

```protobuf
syntax = "proto3";

package notification.endpoint.presentation;

import "notification/endpoint/presentation/create_device.proto";

service NotificationEndpointService {
  // Command
  rpc CreateDevice(CreateDeviceRequest) returns (CreateDeviceResponse) {}
}

```

***notification/endpoint/presentation/create_device.proto***

```protobuf
syntax = "proto3";

package notification.endpoint.presentation;

message CreateDeviceRequest {
  string name = 1;
}

message CreateDeviceResponse {}

```

2. import '{source_root}/notification/endpoint/presentation/service.proto' file in postman

3. set '{source_root}' in postman's import paths

4. show below error
![image](https://github.com/postmanlabs/postman-app-support/assets/20502624/e72a563a-1518-4622-a0b5-510e3f55eb80)

### Operating System

Windows

### Postman Version

10.23.1

### Postman Platform

Postman App

### User Account Type

Signed In User

**Comment by ronork** [comment]
Hey @ChoSeoHwan, I followed your instructions to reproduce the issue, but it appears to be working correctly. Would you mind taking a look at this video to see if you notice anything I may have missed? Thanks for your help.

https://github.com/postmanlabs/postman-app-support/assets/20018997/72d22c1c-d9e9-4502-828e-6a180552eecf

**Comment by ChoSeoHwan** [comment]
Thanks for your comment.

This is a video reproducing my error.

https://github.com/postmanlabs/postman-app-support/assets/20502624/43bf2fb3-2b5f-422e-bdc4-226c0fea46c4


Perhaps this is a problem that occurs in Windows.
For example, is it because of a different path separator than mac/linux?

**Comment by ronork** [comment]
@ChoSeoHwan, thank you for providing the video. I was able to reproduce the issue and will provide an update once a fix has been implemented.

**Comment by ronork** [comment]
@ChoSeoHwan
We have fixed this issue in the latest release of the Postman app (v10.23.5). Can you restart your app to verify if things are working fine for you?

**Comment by ChoSeoHwan** [comment]
The issue has been resolved
Thank you for your efforts
